apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    name: app-server
spec:
  ports:
  - port: 80
    name: http
  selector:
    name: app-server
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-server
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app-server
  template:
    metadata:
      labels:
        name: app-server
    spec:
      containers:
        - name: app-server
          image: gcr.io/$DEVSHELL_PROJECT_ID/app:1.0.0
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: db-config
            items:
            - key: db-config
              path: config.yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-server
spec:
  backend:
    serviceName: app-server
    servicePort: 80
